name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal
  Bluetooth printer.
version: 0.4.1
homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  esc_pos_utils_plus: ^2.0.1+6
  flutter:
    sdk: flutter
  flutter_bluetooth_basic:
    git:
      url: https://github.com/imaldila/flutter_bluetooth_basic_im
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

publish_to: none
